### ISSUE TITLE
[Refactor] 패키지 구조 및 클래스명 변경

### ISSUE THREAD

**Issue by an2z** [saramdle/blog-team-three-CoderHive-BE#46]
## Description
프로젝트 패키지 구조를 계층형에서 도메인형으로 변경하고,
클래스 이름을 알기 쉽게 변경합니다.

## Todo
- [x] 패키지 구조를 도메인형으로 변경
- [x] ERD 변경
- [x] 클래스 이름 변경
- [x] API 문서 변경
- [x] 더미데이터 변경
