### ISSUE TITLE
[Chore] 엔티티명 변경

### ISSUE THREAD

**Issue by an2z** [saramdle/blog-team-three-CoderHive-BE#65]
## Description
엔티티 이름을 변경합니다.

## ToDo
- [x] 모집 기술을 `RecruitmentSkill` → `RecruitSkill`로 변경
- [x] 모집 직무를 `RecruitmentJob` → `RecruitJob`로 변경
- [x] 지원 정보를 `ApplicationInfo` → `ApplyInfo`로 변경
